### ISSUE TITLE
Segfault when dumping the shared cache

### ISSUE THREAD

**Issue by cmsj** [freedomtan/classdump-dyld#1]
I'm running: `./classdump-dyld -o ./headers/ -c` and seeing:

```
  Dumping /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage...(62 classes) (7%)
[1]    96263 segmentation fault  ./classdump-dyld -o headers -c
```

I just upgraded to macOS 11.3, but I hadn't actually used this tool before, so I'm not sure if something broke/changed, or if `-c` generally isn't working.

What I'm actually trying to do is dump `AVFoundation.framework`, so if there's a way to do that from the shared cache, without dumping the entire thing, I'd be very interested to know how :)

**Comment by cmsj** [comment]
fwiw, I added `MPSImage.framework` to the blacklist on line 1544 of main.m and everything else proceeded correctly.

**Comment by freedomtan** [comment]
BTW, if you haven't figured it out yet. The `AVFoundation.framework` is complicated, Apple split the contents into 3 frameworks: `/System/Library/Frameworks/AVFAudio.framework/`,  `/System/Library/PrivateFrameworks/AVFCapture.framework`,                        and `/System/Library/PrivateFrameworks/AVFCore.framework/Versions/A/AVFCore` as shown in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation.tbd`

**Comment by cmsj** [comment]
Yeah that confused me for a bit, but I figured it out. Sadly I have failed to get the bit I wanted, working and I'm out of ideas, but hey, at least classdump-dyld works on 11.3 😁
