### ISSUE TITLE
Running Instructions

### ISSUE THREAD

**Issue by ptrkstr** [freedomtan/classdump-dyld#4]
Hi @freedomtan 
Thanks for extracting this out, I'm also in your position of needing only a M1 macOS class dump.
Hoping you can give me a hand with running this.
This is what I've done:
```
cd ~/classdump-dyld
make
./classdump-dyld_arm64e -o /tmp/foo
```
However my terminal then shows 
```
zsh: killed     ./classdump-dyld_arm64e -o /tmp/foo
```

Did you happen to have an idea?

**Comment by freedomtan** [comment]
my guess is that there may be permission / entitlement problem. I usually use `amfi_get_out_of_my_way=0x1` cf. https://developer.apple.com/forums/thread/680499

**Comment by malhal** [comment]
`classdump-dyld_x86_64` isn't killed (but it doesn't find any headers), very strange

**Comment by ghost** [comment]
> `classdump-dyld_x86_64` isn't killed (but it doesn't find any headers), very strange

I'm seeing the same on macOS 13.2.1. I also disabled SIP and AMFI and tried running `classdump-dyld_arm64e` and `classdump-dyld` but I still get nothing in the output directory.
